#ifndef AEE_EVALUATOR_H 
#define AEE_EVALUATOR_H 
 
#include <memory> 
#include <string> 
#include "Parser.h" 
 
namespace aee { 
 
/** 
* @brief Evaluates parsed arithmetic expressions. 
* 
* This class evaluates an expression tree generated by the parser or executes 
* the full tokenize-parse-evaluate pipeline for a raw expression string. 
*/ 
class Evaluator { 
public: 
    /** 
     * @brief Evaluate an expression tree. 
     * @param root Root node of the expression tree. 
     * @return Integer evaluation result. 
     * @throws std::runtime_error for invalid operations such as division by zero. 
     */ 
    long long evaluate(const std::unique_ptr<ExprNode>& root) const; 
 
    /** 
     * @brief Evaluate a raw user expression. 
     * @param expression Input arithmetic expression. 
     * @return Integer evaluation result. 
     */ 
    long long evaluateExpression(const std::string& expression) const; 
}; 
 
} // namespace aee 
 
#endif 
